### Handle SQL data using Pandas

To connect to any SQL databases, we need to folow below steps:

1. Indentify the SQL Engine to connect to: **PostgeSQL**, **MySQL**, **MSSQL Server** and so on
2. Download and install the corresponding package such as **psycopg2** , **pymysql**, **pyodbc** and so on
3. Download and install **SQL Alchemy** to connect and query database

In [1]:
import pandas as pd

In [3]:
!pip install SQLAlchemy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 15.2 MB/s eta 0:00:00 MB/s eta 0:00:01

[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [4]:
from sqlalchemy import create_engine

In [5]:
# create engine for sqllite
sqll_db = create_engine(url='sqlite:///:memory:')

In [6]:
sqll_db

Engine(sqlite:///:memory:)

In [7]:
import numpy as np

In [10]:
np.random.rand(10)

array([0.59788481, 0.34204617, 0.85201943, 0.7601934 , 0.63575523,
       0.48991559, 0.83792235, 0.03538437, 0.09282631, 0.44253441])

In [12]:
np.linspace(start=2, stop=10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [17]:
np.random.randint(2, 10, size=(4,6))

array([[9, 2, 8, 9, 2, 3],
       [4, 2, 5, 4, 6, 4],
       [5, 2, 3, 9, 2, 7],
       [9, 9, 4, 8, 6, 4]])

In [20]:
np.linspace(start=2, stop=10, num=20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [21]:
np.random.rand(3,4)

array([[0.48516196, 0.43859335, 0.64196121, 0.63860675],
       [0.43623245, 0.12461638, 0.19504176, 0.4084879 ],
       [0.93850454, 0.9627068 , 0.58496997, 0.4358391 ]])

In [24]:
np.random.randint(2,12, size=(6,4))

array([[ 9,  6,  9,  3],
       [ 4,  9,  5,  2],
       [ 7,  6,  6,  2],
       [11,  5,  6,  3],
       [10,  5, 10, 10],
       [10, 10,  8,  7]])

In [27]:
df = pd.DataFrame(data=np.random.randint(2,12, size=(6,4)), columns=['x1', 'x2', 'x3', 'x4'])

In [28]:
df

x1  x2  x3  x4
0  10   4   6   6
1   6   5   5   6
2   6   7   2  11
3   9   4   4   4
4   8   9   8   5
5   8   8   7   2

In [29]:
# save this as table in database sqll_db
df.to_sql(name='tableone', con=sqll_db)

6

In [32]:
df = pd.read_sql(sql='tableone', con=sqll_db)

In [33]:
df

index  x1  x2  x3  x4
0      0  10   4   6   6
1      1   6   5   5   6
2      2   6   7   2  11
3      3   9   4   4   4
4      4   8   9   8   5
5      5   8   8   7   2

In [37]:
# run SQL query on this sql object
df = pd.read_sql_query(sql='SELECT x1,x2 FROM tableone', con=sqll_db)

In [38]:
df

x1  x2
0  10   4
1   6   5
2   6   7
3   9   4
4   8   9
5   8   8