In [1]:
import numpy as np

In [2]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
# Arithmetic operations
narr = np.arange(20)

In [4]:
narr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
narr + 2 # add 2 to each element in numpy arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [7]:
narr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [9]:
narr / narr # getting warning as 0/0 is invalid divison

/var/folders/td/6114ll7x64q8z0y3spxdq7900000gn/T/ipykernel_94435/2861030997.py:1: RuntimeWarning: invalid value encountered in divide
  narr / narr # getting warning as 0/0 is invalid divison


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
0 / 0 # in Python we get the error but nupy handles it internally and return warning

ZeroDivisionError: division by zero

In [16]:
narr + narr # make sure when we are performing arithmetic operations on 2 arrays, it must be of same size

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [17]:
narr * narr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [19]:
narr.max()

np.int64(19)

In [20]:
narr.min()

np.int64(0)

In [22]:
narr.mean()

np.float64(9.5)

In [23]:
narr.std()

np.float64(5.766281297335398)

In [25]:
len(narr)

20

In [26]:
np.sqrt(narr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [27]:
np.max(narr)

np.int64(19)

In [28]:
np.log(narr)

/var/folders/td/6114ll7x64q8z0y3spxdq7900000gn/T/ipykernel_94435/2214490810.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(narr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [30]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
np.arange(20).reshape(5,4).sum()

np.int64(190)

In [33]:
np.sum(np.arange(20).reshape(5,4), axis=0)

array([40, 45, 50, 55])

In [34]:
np.sum(np.arange(20).reshape(5,4), axis=1)

array([ 6, 22, 38, 54, 70])